services:
  postgres:
    image: elizabethbbakul/postgres
    container_name: postgres
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - ${POSTGRES_PORT}:5432
    build:
      context: ./database
    restart: unless-stopped
  itmo-task:
    image: elizabethbbakul/course_work_medical
    depends_on:
      - postgres
    build: .
    ports:
      - ${TASK_PORT}:8080
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
volumes:
  postgres:
